name: API Sync and SDK Update

on:
  push:
    branches:
      - main

jobs:
  sync-api-and-build-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Compare and update API spec
        id: api-sync
        env:
          API_URL: https://ci-cd-integration.onrender.com
        run: |
          # Download API spec
          curl -s $API_URL/openapi-json > sdk-control/api.json
          echo "spec_changed=true" >> "$GITHUB_OUTPUT"

      - name: Install liblab
        if: steps.api-sync.outputs.spec_changed == 'true'
        run: |
          npm install -g liblab

      - name: Build SDK if API spec changed
        if: steps.api-sync.outputs.spec_changed == 'true'
        env:
          LIBLAB_TOKEN: ${{ secrets.LIBLAB_TOKEN }}
        run: |
          cd sdk-control
          liblab build --pr
          