name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.event.head_commit.message != 'Update downloaded API spec' && github.event.head_commit.message != 'Bump sdk version'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deployment
        id: trigger-deploy
        run: |
          RESPONSE=$(curl -s -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }})
          DEPLOY_ID=$(echo $RESPONSE | jq -r '.deploy.id')
          echo "deploy_id=$DEPLOY_ID" >> "$GITHUB_OUTPUT"

      - name: Wait for deployment
        id: wait-deploy
        timeout-minutes: 5
        run: |
          DEPLOY_ID=${{ steps.trigger-deploy.outputs.deploy_id }}
          
          while true; do
            RESPONSE=$(curl -s -X GET \
              -H "accept: application/json" \
              -H "authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
              "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys/$DEPLOY_ID")
            
            STATUS=$(echo $RESPONSE | jq -r '.status')
            
            if [ "$STATUS" = "live" ]; then
              echo "Deployment is live!"
              echo "status=live" >> "$GITHUB_OUTPUT"
              exit 0
            elif [ "$STATUS" = "failed" ]; then
              echo "Deployment failed"
              exit 1
            fi
            
            echo "Current status: $STATUS"
            sleep 10
          done

      - name: Trigger API Sync
        if: steps.wait-deploy.outputs.status == 'live'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'api-sync.yml',
              ref: context.ref
            }); 